spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul
    username: root
    password: soso1224

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        color-codes: true
        use_sql_comments: true
    defer-datasource-initialization: true


  output:
    ansi:
      enabled: ALWAYS

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 338624824075-rrqtn59dl2ub36lctrb9tg3tfel196jg.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace

jwt:
  key: stackoverflow123412341234123412341234
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
