spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        color-codes: true
        use_sql_comments: true
    defer-datasource-initialization: true


  output:
    ansi:
      enabled: ALWAYS

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${G.CLIENT.ID}
            clientSecret: ${G.CLIENT.SECRET}
            scope:
              - email
              - profile


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace

jwt:
  key: stackoverflow123412341234123412341234
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
